name: Compiling Java Application
 
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history to ensure access to all branches and commits
 
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: rewrite code
      run: |
        sudo apt install maven -y
        mvn -version
        cd Calculator-master
        mvn install
        mvn rewrite:run
    
 
    - name: Compile Java files
      run: |
        javac *.java
